---
name: Regression checks
"on":
  push:
    branches:
      - '**'
  schedule:  # Weekly runs to pick up on bitrot
    - cron: '37 23 * * 0'

defaults:
  run:
    shell: bash

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.24.1, lts/*, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v7
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - name: Show versions
        run: |
          npm --version
          node --version
      - name: Install packages
        run: npm ci || npm install  # 10.24.1 doesn't grok "ci"
      - name: Syntax check
        run: npm run check
      - name: Regression tests
        run: npm run test
      - name: Package audit
        if: matrix.node-version == 'latest'
        run: npm audit
  release-checks:
    name: Package but don't release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup nodejs
        uses: actions/setup-node@v7
        with:
          node-version: current
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Package
        run: npm pack
